plugins { id 'com.android.application' }

dependencies {
    implementation "androidx.annotation:annotation:1.9.1"
    def media3_version = '1.10.1'
    implementation "androidx.media3:media3-exoplayer:$media3_version"
    implementation "androidx.media3:media3-exoplayer-hls:$media3_version"
    implementation "androidx.media3:media3-exoplayer-dash:$media3_version"
    implementation "androidx.media3:media3-ui:$media3_version"
}

android {
    namespace 'com.seyirplus.m3utv'
    compileSdk 36

    defaultConfig {
        applicationId 'com.seyirplus.m3utv'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
